<?php
/******************************************
Dutch
Admin Category Language
******************************************/

$lang['categories']				= 'Categorieën';
$lang['error_must_select']			= 'Je moet een categorie selecteren om te organiseren';
$lang['error_not_found']			= 'De gevraagde categorie kon niet gevonden worden.';
$lang['organize_category']			= 'Organiseren "%s" Categorie';
$lang['organize']				= 'Organiseren';
$lang['category_id']				= 'ID';
$lang['category_form']				= 'Categorie Vorm';
$lang['name']					= 'Naam';
$lang['slug']					= 'URL trefwoord';
$lang['description']				= 'Beschrijving';
$lang['excerpt']				= 'Uittreksel';
$lang['sequence']				= 'Sequence';
$lang['image']					= 'Afbeelding';
$lang['seo_title']				= 'SEO Titel';
$lang['meta']					= 'Meta gegevens';
$lang['message_category_saved']                 = 'De categorie is gered!';
$lang['error_file_upload']			= '<p>You did not select a file to upload.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category']                = 'De categorie is verwijderd.';
$lang['current_file']				= 'Huidig ​​bestand';
$lang['confirm_delete_category']                = 'Weet je zeker dat je deze categorie wilt verwijderen?';
$lang['add_new_category']			= 'Nieuwe categorie toevoegen';
$lang['no_categories']				= 'Er zijn geen categorieën';
$lang['attributes']				= 'Attributen';
$lang['seo']					= 'SEO';
$lang['parent']					= 'Ouder';
$lang['meta_data_description']                  = 'ex. &lt;meta name="omschrijving" content="Wij verkopen producten die u helpen" /&gt;';
$lang['drag_and_drop']				= 'Slepen en neerzetten van de producten in de bestelling zou u ze graag.';
$lang['sku']					= 'SKU';
$lang['price']					= 'Prijs';
$lang['sale']					= 'Verkoop';
$lang['max_file_size']				= 'Maximale bestandsgrootte';



$lang['vinyl']                                  = 'Vinyl';
$lang['face_masks']				= 'Gezichtsmaskers';
$lang['dental_bibs']				= 'Dentale bibs';
$lang['samples']				= 'Monsters';
$lang['system']                                 = 'Systeem';
$lang['shop']                                   = 'Winkel';
$lang['edit']                                   = 'Bewerken';

$lang['soft_nirile']                            = 'Soft Nitrile';

$lang['name_nl']				= 'Naam Nederland';
$lang['name_be']				= 'Naam België,Nederlands';
$lang['name_de']				= 'Naam Duitsland';
$lang['name_au']				= 'Naam Oostenrijk';
$lang['name_fr']				= 'Naam Frankrijk';
$lang['name_bel']				= 'Naam België,Franse';
$lang['name_lx']				= 'Naam Luxemburg';
$lang['name_uk']				= 'Naam Verenigd Koninkrijk';

$lang['add_category']				= 'Categorie toevoegen';
$lang['edit_category']				= 'Categorie bewerken';
$lang['general']				= 'Algemeen';
$lang['features']				= 'Functies';






































