<?php
/******************************************
US English
Admin Category Language
******************************************/

$lang['categories']				= 'Categories';
$lang['error_must_select']			= 'You must select a category to organize';
$lang['error_not_found']			= 'The requested category could not be found.';
$lang['organize_category']			= 'Organize "%s" Category';
$lang['organize']				= 'Organize';
$lang['category_id']				= 'ID';
$lang['category_form']				= 'Category Form';
$lang['name']					= 'Name';
$lang['slug']					= 'URL keyword';
$lang['description']				= 'Description';
$lang['excerpt']				= 'Excerpt';
$lang['sequence']				= 'Sequence';
$lang['image']					= 'Image';
$lang['seo_title']				= 'SEO Title';
$lang['meta']					= 'Meta Data';
$lang['message_category_saved']                 = 'The category has been saved!';
$lang['error_file_upload']			= '<p>You did not select a file to upload.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category']                = 'The category has been deleted.';
$lang['current_file']				= 'Current File';
$lang['confirm_delete_category']                = 'Are you sure you want to delete this category?';
$lang['add_new_category']			= 'Add New Category';
$lang['no_categories']				= 'There are currently no categories';
$lang['attributes']				= 'Attributes';
$lang['seo']					= 'SEO';
$lang['parent']					= 'Parent';
$lang['meta_data_description']                  = 'ex. &lt;meta name="description" content="We sell products that help you" /&gt;';
$lang['drag_and_drop']				= 'Drag and drop the products in the order you would like them to appear.';
$lang['sku']					= 'SKU';
$lang['price']					= 'Price';
$lang['sale']					= 'Sale';
$lang['max_file_size']				= 'Max File Size';


$lang['soft_nitrile']				= 'Soft nitrile';
$lang['vinyl']                                  = 'Vinyl';
$lang['face_masks']				= 'Face masks';
$lang['dental_bibs']				= 'Dental bibs';
$lang['samples']				= 'Samples';
$lang['system']                                 = 'System';
$lang['shop']                                   = 'Shop';
$lang['edit']                                   = 'Edit';

$lang['soft_nirile']                            = 'Soft Nitrile';

$lang['name_nl']					= 'Name Netherlands';
$lang['name_be']					= 'Name Belgium,Dutch';
$lang['name_de']					= 'Name Germany';
$lang['name_au']					= 'Name Austria';
$lang['name_fr']					= 'Name France';
$lang['name_bel']					= 'Name Belgium,French';
$lang['name_lx']					= 'Name Luxembourg';
$lang['name_uk']					= 'Name United Kingdom';

$lang['add_category']				= 'Add category';
$lang['edit_category']				= 'Edit category';
$lang['general']					= 'General';
$lang['features']					= 'Features';






































